const GSTCodeState = [
  { code: 28, state: "Andhra Pradesh" },
  { code: 37, state: "Andhra Pradesh" },
  { code: 35, state: "Andaman And Nicobar Islands" },
  { code: 12, state: "Arunachal Pradesh" },
  { code: 18, state: "Assam" },
  { code: 10, state: "Bihar" },
  { code: 4, state: "Chandigarh" },
  { code: 22, state: "Chattisgarh" },
  { code: 99, state: "Centre Jurisdiction" },
  { code: 7, state: "Delhi" },
  { code: 26, state: "Dadra And Nagar Haveli And Daman And Diu" },
  { code: 24, state: "Gujarat" },
  { code: 6, state: "Haryana" },
  { code: 2, state: "Himachal Pradesh" },
  { code: 20, state: "Jharkhand" },
  { code: 29, state: "Karnataka" },
  { code: 32, state: "Kerala" },
  { code: 38, state: "Ladakh" },
  { code: 31, state: "Lakshadweep" },
  { code: 14, state: "Manipur" },
  { code: 27, state: "Maharashtra" },
  { code: 17, state: "Meghalaya" },
  { code: 15, state: "Mizoram" },
  { code: 13, state: "Nagaland" },
  { code: 21, state: "Odisha" },
  { code: 30, state: "Goa" },
  { code: 1, state: "Jammu and Kashmir" },
  { code: 19, state: "West Bengal" },
  { code: 5, state: "Uttarakhand" },
  { code: 9, state: "Uttar Pradesh" },
  { code: 34, state: "Puducherry" },
  { code: 3, state: "Punjab" },
  { code: 8, state: "Rajasthan" },
  { code: 11, state: "Sikkim" },
  { code: 36, state: "Telangana" },
  { code: 33, state: "Tamil Nadu" },
  { code: 16, state: "Tripura" },
  { code: 23, state: "Madhya Pradesh" },
  { code: 97, state: "Other Territory" },
];

export default GSTCodeState;
